### ISSUE TITLE
您好

### ISSUE THREAD

**Issue by Joyxj** [xwgeng/RNNSearch#1]
请问一下您这边数据从哪里下载呢？

**Comment by xwgeng** [comment]
The training corpus for Chinese-English translation includes LDC2002E18, LDC2003E07, LDC2003E14, Hansards portion of LDC2004T07, LDC2004T08, and LDC2005T06. Unfortunately, the LDC corpora are not free. Instead, you can use the WMT17 dataset for Chinese-English, German-English, etc from [WMT 17 translation task](http://www.statmt.org/wmt17/translation-task.html#download)

**Comment by Joyxj** [comment]
thank you!

**Comment by huimiesj** [comment]
can you add my QQ1924802304,I can buy the LDC corpa
