### ISSUE TITLE
Missing path folder

### ISSUE THREAD

**Issue by sanjita-suresh** [xwgeng/RNNSearch#3]
I was trying this tutorial to build a NMT from chinese-english but I am getting error in building vocabulary as --corpus /path/to/train.cn is missing.

**Comment by xwgeng** [comment]
To construct the vocabulary, just replace `/path/to/train.cn` with the path of your training data.

**Comment by sanjita-suresh** [comment]
Thank you Geng.

Can you please tell me where can I get the training data for
Chinese-English?

**Comment by xwgeng** [comment]
https://github.com/xwgeng/RNNSearch/issues/1#issuecomment-411312606

**Comment by sanjita-suresh** [comment]
Thanks a lot. I will try the wmt Training data.
